server:
  port: 8081  # Let Spring Boot choose a random available port

spring:
  application:
    name: core-banking-system
  datasource:
    password: 9840115582
    url: jdbc:mysql://localhost:3306/account
    username: root
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
