server:
  port: 0  # Let Spring Boot choose a random available port

spring:
  application:
    name: foneloan-central-system

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Any custom configs for this service
loan:
  decision:
    max-amount: 5000
